# -*- coding: utf-8 -*-
"""Tugas_Pra_UTS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rg3ufBY58mt_94w_enb0M2eTHxE0Y-wu

# Proyek Analisis Data: Bike Sharing
- Kelompok : IF7 - Scrapy
- Anggota : </br>
10122238 - TITAN EL HAQI</br>
10122241 - MARSYA AWLIYA SABRINA</br>
10122254 - ARIQ HIKARI HIDAYAT</br>
10122257 - M.GHAZY AL H.H</br>
10122260 - ADISYA AINUN FATIHAH</br>
10122264 - MUHAMMAD NAUFAL GHIFARI </br>

## Menentukan Pertanyaan Bisnis

1. Bagaimana perbandingan jumlah peminjaman sepeda antara tahun 2011 dan 2012? (10122238 - Titan El Haqi)
2. Apakah ada penurunan signifikan dalam penggunaan sepeda saat cuaca buruk? (10122241 - Marsya Awliya Sabrina)
3. Apakah ada pengaruh hari libur terhadap jumlah sepeda yang disewa? (10122254 - Ariq Hikari Hidayat)
4. Apa pengaruh faktor cuaca terhadap jumlah sewa sepeda harian? (10122257 - M. Ghazy Al H. H.)
5. Bagaimana cara mendeteksi peristiwa atau anomali dalam data penyewaan sepeda? (10122260 - Adisya Ainun Fatihah)
6. Bagaimana Distribusi Waktu Peminjaman Sepeda? (10122264 - Muhammad Naufal Ghifari)

## Menyiapkan semua library yang dibutuhkan
"""

import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

# menentukan dataset apa yang akan dipakai
day_df = pd.read_csv('https://ariqhikari.github.io/data/bike-sharing-dataset/day.csv')
day_df.head()

hour_df = pd.read_csv('https://ariqhikari.github.io/data/bike-sharing-dataset/hour.csv')
hour_df.head()

"""### Assessing Data"""

# memeriksa missing-values/duplikat
# menentukan atribut yang akan dipakai

"""#### Menilai tabel `day_df`"""

day_df.info()

day_df.isna().sum()

print("Jumlah duplikasi: ", day_df.duplicated().sum())

day_df.describe()

"""#### Menilai tabel `hour_df`"""

hour_df.info()

day_df.nunique()

print("Jumlah duplikasi: ",hour_df.duplicated().sum())

hour_df.describe()

"""### Cleaning Data"""

# jika ada missing-values/duplikat, tentukan ingin diapakan (transformasi/hapus)

"""#### Membersihkan tabel `day_df`

##### Duplicate data
"""

day_df.duplicated().sum()

day_df.drop_duplicates(inplace=True)

print("Jumlah duplikasi: ", day_df.duplicated().sum())

"""##### Missing values"""

day_df.isna().sum()

"""##### Inaccurate value"""

day_df.describe()

"""##### Memperbaiki tipe data"""

day_df['dteday'] = pd.to_datetime(day_df['dteday'])

day_df.info()

"""#### Membersihkan tabel `hour_df`

##### Memperbaiki tipe data
"""

hour_df.info()

hour_df['dteday'] = pd.to_datetime(hour_df['dteday'])

hour_df.info()

"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

# eksplor data

# Filter cnt dan dteday dari dataset
dteday_cnt = day_df.groupby('dteday')
cpy = dteday_cnt['cnt'].sum().reset_index() #count per year

# Ups bagi 2, jadi 2011 dan 2012
cnt2011 = cpy[cpy['dteday'].dt.year == 2011]
cnt2012 = cpy[cpy['dteday'].dt.year == 2012]

# Jumlahkan total penyewa
total2011 = cnt2011['cnt'].sum()
total2012 = cnt2012['cnt'].sum()

# Menghitung rata-rata jumlah sewa sepeda berdasarkan kondisi cuaca
average_rentals_by_weather = day_df.groupby('weathersit')['cnt'].mean().reset_index()

# Tren harian (NAUFAL)
daily_trend = hour_df.groupby('hr')['cnt'].mean().reset_index()

# Tren musiman (berdasarkan hari dalam seminggu)
weekly_seasonal_trend = hour_df.groupby(['weekday', 'hr'])['cnt'].mean().reset_index()

# Pisahkan data menjadi dua kelompok: hari libur dan bukan hari libur
holiday_data = hour_df[hour_df['holiday'] == 1]
non_holiday_data = hour_df[hour_df['holiday'] == 0]

# Hitung rata-rata jumlah sepeda yang disewa pada hari libur dan bukan hari libur
avg_rental_holiday = holiday_data['cnt'].mean()
avg_rental_non_holiday = non_holiday_data['cnt'].mean()

# Hitung rata-rata dan standar deviasi bergulir dari jumlah penyewaan sepeda
rolling_mean = day_df['cnt'].rolling(window=30).mean()
rolling_std = day_df['cnt'].rolling(window=30).std()

# Identifikasi anomali sebagai titik yang lebih dari 3 standar deviasi dari rata-rata bergulir
anomalies = day_df[abs(day_df['cnt'] - rolling_mean) > 3 * rolling_std]

# Filter data untuk cuaca buruk (misalnya, weathersit 3 dan 4)
bad_weather_data = hour_df[hour_df['weathersit'].isin([3, 4])]

# Hitung total rental sepeda untuk setiap jam pada cuaca buruk
total_rentals_bad_weather = bad_weather_data.groupby('hr')['cnt'].sum()

# Hitung total rental sepeda untuk setiap jam pada semua kondisi cuaca
total_rentals_all_weather = hour_df.groupby('hr')['cnt'].sum()

# Hitung persentase penurunan dalam penggunaan sepeda saat cuaca buruk
percentage_reduction = ((total_rentals_all_weather - total_rentals_bad_weather) / total_rentals_all_weather) * 100

"""## Visualization & Explanatory Analysis

###Pertanyaan 1:
"""

plt.bar(['2011','2012'], [total2011, total2012], color='lightblue')

plt.title('Perbandingan Jumlah Penyewa Sepeda, 2011 dan 2012')
plt.ylabel('Jumlah Penyewa')
plt.xlabel('Tahun')
plt.show()

"""###Pertanyaan 2:"""

plt.figure(figsize=(10, 6))
plt.plot(percentage_reduction, marker='o')
plt.title('Persentase Penurunan Penggunaan Sepeda saat Cuaca Buruk')
plt.xlabel('Jam (0-23)')
plt.ylabel('Persentase Penurunan')
plt.grid(True)
plt.show()

"""### Pertanyaan 3:"""

plt.bar(['Weekend', 'Weekday'], [avg_rental_holiday, avg_rental_non_holiday])
plt.title('Rata-rata Penyewaan Sepeda pada Hari Libur vs Non-Libur')
plt.ylabel('Jumlah Rata-Rata Penyewaan Sepeda')
plt.show()

"""### Pertanyaan 4"""

plt.figure(figsize=(10, 6))
plt.bar(average_rentals_by_weather['weathersit'], average_rentals_by_weather['cnt'], color='skyblue')
plt.title('Rata-rata Jumlah Sewa Sepeda Berdasarkan Kondisi Cuaca')
plt.xlabel('Kondisi Cuaca')
plt.ylabel('Rata-rata Jumlah Sewa Sepeda')
plt.xticks(rotation=90)
plt.show()

"""### Pertanyaan 5:"""

plt.plot(day_df['dteday'], day_df['cnt'])
plt.scatter(anomalies['dteday'], anomalies['cnt'], c='red')
plt.xlabel('Tanggal')
plt.ylabel('Jumlah penyewaan sepeda')
plt.xticks(rotation=90)
plt.show()

"""### Pertanyaan 6:"""

#Visualisasi harian
plt.figure(figsize=(12, 6))
sns.lineplot(x='hr', y='cnt', data=daily_trend, errorbar=None)
plt.title('Distribusi Harian Peminjaman Sepeda')
plt.xlabel('Jam')
plt.ylabel('Rata-rata Jumlah Peminjam')
plt.show()

#Visualisasi musiman
plt.figure(figsize=(14, 7))
sns.lineplot(x='hr', y='cnt', hue='weekday', data=weekly_seasonal_trend, errorbar=None)
plt.title('Distribusi Musiman Penyewaan Sepeda (Berdasarkan Hari dalam Seminggu)')
plt.xlabel('Jam')
plt.ylabel('Rata-rata Jumlah Penyew')
plt.legend(title='Hari dalam Seminggu', loc='upper left', bbox_to_anchor=(1, 1))
plt.show()

"""## Conclusion

<!-- menyimpulkan dari pertanyaan bisnis, analisis data, dan visualisasi data nya -->
- Conclution pertanyaan 1<br>
Dilihat dari analisis pada dataset Bike Sharing, terdapat peningkatan jumlah penyewa dari tahun 2011 ke tahun 2012 sebanyak 64.87%. Hasil ini didapatkan dari mengambil selisih penyewa pada tahun 2011 dan 2012, kemudian dibagi dengan total penyewa pada tahun 2011.
- Conclution pertanyaan 2<br>
Berdasarkan analisis menggunakan dataset sepeda, tampaknya ada potensi penurunan signifikan dalam penggunaan sepeda saat cuaca buruk. Analisis dilakukan dengan membandingkan total rental sepeda untuk setiap jam pada kondisi cuaca buruk dengan total rental sepeda pada semua kondisi cuaca. Hasilnya dapat divisualisasikan dalam bentuk grafik persentase penurunan penggunaan sepeda pada berbagai jam. Kesimpulan akhirnya bergantung pada pola yang terlihat dalam grafik tersebut.
- Conclution pertanyaan 3<br>
Berdasarkan analisis data, terdapat perbedaan yang signifikan dalam rata-rata jumlah sepeda yang disewa antara hari libur dan bukan hari libur. Visualisasi menunjukkan bahwa rata-rata peminjaman sepeda lebih tinggi pada hari-hari yang bukan hari libur. Oleh karena itu, dapat disimpulkan bahwa hari libur memiliki pengaruh terhadap pola peminjaman sepeda, dengan potensi menurunnya permintaan pada hari libur dibandingkan dengan hari-hari biasa.
- Conclution pertanyaan 4<br>
Kondisi cuaca berpengaruh pada jumlah sewa sepeda harian, dan kondisi cuaca yang lebih baik cenderung meningkatkan jumlah sewa sepeda. Namun, cuaca sedang memiliki variasi yang lebih besar dalam jumlah sewa.
- Conclution pertanyaan 5<br>
Peristiwa atau anomali dalam data penyewaan sepeda dapat dideteksi menggunakan berbagai teknik, seperti metode statistik, algoritma pembelajaran mesin, atau algoritma pembelajaran tidak terbimbing. Salah satu metode sederhana dan mudah diterapkan adalah dengan menggunakan standar deviasi bergulir. Standar deviasi bergulir adalah rata-rata dari standar deviasi dari serangkaian data dalam periode waktu tertentu. Standar deviasi bergulir dapat digunakan untuk melacak perubahan dalam variabilitas data dari waktu ke waktu, dan untuk mengidentifikasi anomali.
- Conclution pertanyaan 6<br>
Terdapat peningkatan peminjaman pada jam-jam tertentu, khususnya selama periode sibuk pergi dan pulang kerja.
"""